### ISSUE TITLE
Operation -- Set or try to get automatically ?

### ISSUE THREAD

**Issue by helio-frota** [bucharest-gold/hawkular-apm-client#6]
https://github.com/bucharest-gold/hawkular-apm-client/blob/master/index.js#L46-L55

**Comment by balunasj** [comment]
Who needs to answer this?

**Comment by helio-frota** [comment]
@balunasj well, I dunno maybe @lance and @objectiser
if this is component it can be anything [right ?]
https://github.com/bucharest-gold/hawkular-apm-client/blob/master/index.js#L45-L47

**Comment by objectiser** [comment]
In theory, the operation can be anything - its just for HTTP communications we have been using the HTTP method as the operation name, and then recording the URL path.

**Comment by helio-frota** [comment]
@objectiser thanks for the information.

When I mentioned 'objectiser' was exactly because I know you wrote about this in the past but I don't remembered. 

And by mentioning 'lance' is to get help if we going to get this information automatically, because if this can be `anything` , then:

or we add a hard coded constant value 

or automatically [ how to do it? ].

**Comment by lance** [comment]
So I think for now, we should assume that the operation is the HTTP method. But I also think this points to the fact that the hawkular apm client should be configurable in a way that allows users to somehow map asynchronous entry points to an operation name in the case of a component. This is a bigger, overall design issue, and something that I think could in fact effect more than just this client. For one, I think it may point to a need for greater flexibility in lightbright.

**Comment by helio-frota** [comment]
closing , we can open again in a future case needed.
