### ISSUE TITLE
Document about the required delay ?

### ISSUE THREAD

**Issue by helio-frota** [bucharest-gold/hawkular-apm-client#7]
Our test has a delay: https://github.com/bucharest-gold/hawkular-apm-client/blob/master/test/client-test.js#L41

This is to wait the data persist into hawkular-apm-server.

Our tape tests are doing the following operations:
1. Access an fake app to catch traces.
   
   1.1. The fake app [_using hawkular-apm-client that uses lightbright and roi_] is sending traces to hawkular-apm-server.
2. `delay added here` Access the hawkular apm server to check if traces was added.

Without this delay just before item 2. we get zero results.

Also, we can see some delay added on hawkular apm server tests:

https://github.com/hawkular/hawkular-apm/blob/60100941363a8ee52294411611e0f60a3458f886/tests/dist/src/test/java/org/hawkular/apm/tests/dist/TraceServiceITest.java#L167-L168

**Comment by balunasj** [comment]
It would be good to explain why the delay is there.

**Comment by helio-frota** [comment]
closing , we can open again in a future case needed.
