### ISSUE TITLE
Propagating state information with service communications

### ISSUE THREAD

**Issue by objectiser** [bucharest-gold/hawkular-apm-client#8]
To enable a trace instance to follow the flow of a conversation across multiple services, it is necessary to piggyback an id on the communications between the services, and then have the tracing component on the receiving service intercept that id and associated with the APM trace fragment's Consumer node as a correlation id.

Is this going to be possible with the lightbright?

**Comment by lance** [comment]
@objectiser I think this is the responsibility of hawkular-apm-client and not lightbright itself. For clarity, all lightbright does is allow us to trace asynchronous entry points and link those with the eventual execution of a chunk of asynchronous code. That little bit of capability is extremely useful and can be built on to provide some good insight, but I would prefer to keep its capabilities quite simple. 

How is the ID typically transmitted in the case of HTTP services - via a header? That's a much higher level than lightbright is operating at. I believe the hawkular client could act as the recipient of this ID by extracting it from a header, and then append the ID to the JSON data that is ultimately submitted to the server. 

Of course I could be completely misunderstanding the flow.

**Comment by helio-frota** [comment]
I agree.

**Comment by objectiser** [comment]
@lance yes the id is passed via http headers - and it is fine if it sits outside lightbright scope - just wasn't sure where the responsibility might be.

**Comment by helio-frota** [comment]
bucharest-gold/entente#133

**Comment by helio-frota** [comment]
closing , we can open again in a future case needed.
